# Generated by Django 3.2.21 on 2023-09-09 09:29

from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('molecule', django_rdkit.models.fields.MolField()),
            ],
        ),
    ]
