# Generated by Django 3.2.22 on 2023-10-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_species_molecular_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='lower_state_degeneracy',
            field=models.IntegerField(null=True),
        ),
    ]
