# Generated by Django 3.2.23 on 2024-02-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240203_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinelist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linelist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
