# Generated by Django 3.2.22 on 2023-11-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_line_lower_state_degeneracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='vib_qn',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
