# Generated by Django 3.2.23 on 2024-02-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240203_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallinelist',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='linelist',
            name='approved',
        ),
        migrations.AddField(
            model_name='historicallinelist',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linelist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_linelists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linelist',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_linelists', to=settings.AUTH_USER_MODEL),
        ),
    ]
