# Generated by Django 3.2.23 on 2024-02-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240203_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallinelist',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='linelist',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='historicallinelist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linelist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
