# Generated by Django 3.2.23 on 2023-11-02 20:32

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_line_vib_qn'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmetadata',
            name='qpart_file',
            field=models.FileField(default=0, upload_to=core.models.sp_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['qpart'])]),
            preserve_default=False,
        ),
    ]
