# Generated by Django 3.2.23 on 2023-11-03 21:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_speciesmetadata_qpart_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='pickett_lower_state_qn',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='pickett_qn_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='pickett_upper_state_qn',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='upper_state_degeneracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='upper_state_energy',
            field=core.models.ArbitraryDecimalField(null=True),
        ),
    ]
