# Generated by Django 3.2.23 on 2024-02-04 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240203_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linelist',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
