# Generated by Django 3.2.23 on 2023-11-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231103_2151'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='line',
            index=models.Index(fields=['frequency'], name='core_line_frequen_cc6179_idx'),
        ),
    ]
