# Generated by Django 3.2.23 on 2023-11-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_line_core_line_frequen_cc6179_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='pickett_lower_state_qn',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='line',
            name='pickett_upper_state_qn',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
