# Generated by Django 3.2.23 on 2024-02-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240204_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetareference',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmetareference',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalspecies',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalspecies',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metareference',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metareference',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='species',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalline',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicallinelist',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='linelist',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
