# Generated by Django 3.2.23 on 2024-02-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240207_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalline',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='line',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='line',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='line',
            name='uploaded_by',
        ),
    ]
