# Generated by Django 3.2.23 on 2024-02-08 19:50

import core.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240208_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='cat_file',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cat'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='cat_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=core.models.sp_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cat'])]),
            preserve_default=False,
        ),
    ]
