# Generated by Django 3.2.23 on 2024-02-08 19:52

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240208_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspeciesmetadata',
            name='cat_file',
            field=models.TextField(max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cat'])]),
        ),
        migrations.AlterField(
            model_name='speciesmetadata',
            name='cat_file',
            field=models.FileField(null=True, upload_to=core.models.sp_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cat'])]),
        ),
    ]
