# Generated by Django 3.2.24 on 2024-02-14 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240214_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linelist',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linelist_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metareference',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_reference_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reference',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='species',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speciesmetadata',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_metadata_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
