# Generated by Django 3.2.24 on 2024-02-16 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20240215_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approver',
        ),
        migrations.AddField(
            model_name='user',
            name='approver',
            field=models.ManyToManyField(db_index=True, related_name='dependent_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
