# Generated by Django 3.2.24 on 2024-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20240216_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalline',
            name='contains_rovibrational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='qn_label_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='line',
            name='contains_rovibrational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='qn_label_str',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
