# Generated by Django 3.2.24 on 2024-02-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20240220_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalline',
            name='contains_rovibrational',
        ),
        migrations.RemoveField(
            model_name='historicalline',
            name='qn_label_str',
        ),
        migrations.RemoveField(
            model_name='line',
            name='contains_rovibrational',
        ),
        migrations.RemoveField(
            model_name='line',
            name='qn_label_str',
        ),
    ]
