# Generated by Django 3.2.24 on 2024-03-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20240220_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speciesmetadata'),
        ),
        migrations.AlterField(
            model_name='metareference',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speciesmetadata'),
        ),
        migrations.AlterField(
            model_name='metareference',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reference'),
        ),
    ]
