# Generated by Django 3.2.24 on 2024-03-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20240304_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalline',
            name='contains_rovibrational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='qn_label_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='contains_rovibrational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='qn_label_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='vib_qn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='line',
            name='contains_rovibrational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='qn_label_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='contains_rovibrational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='qn_label_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='vib_qn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='metareference',
            unique_together={('meta', 'ref')},
        ),
    ]
