# Generated by Django 3.2.24 on 2024-03-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20240315_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspeciesmetadata',
            name='contains_rovibrational',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='speciesmetadata',
            name='contains_rovibrational',
            field=models.BooleanField(blank=True),
        ),
    ]
