# Generated by Django 3.2.24 on 2024-03-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20240315_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='cat_file_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='cat_file_added',
            field=models.BooleanField(default=False),
        ),
    ]
