# Generated by Django 3.2.25 on 2024-04-01 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_historicalspeciesmetadatamiscfileupload_speciesmetadatamiscfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sp_misc_files', to='core.user'),
            preserve_default=False,
        ),
    ]
