# Generated by Django 3.2.25 on 2024-04-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20240401_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='name',
            field=models.CharField(default='name2', max_length=255),
            preserve_default=False,
        ),
    ]
