# Generated by Django 3.2.25 on 2024-04-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20240401_2023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speciesmetadatamiscfileupload',
            unique_together={('meta', 'name')},
        ),
    ]
