# Generated by Django 3.2.25 on 2024-04-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_speciesmetadatamiscfileupload_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='speciesmetadatamiscfileupload',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='speciesmetadatamiscfileupload',
            name='name',
        ),
    ]
