# Generated by Django 3.2.25 on 2024-04-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20240401_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
