# Generated by Django 3.2.25 on 2024-04-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20240401_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='name',
        ),
        migrations.RemoveField(
            model_name='speciesmetadatamiscfileupload',
            name='name',
        ),
    ]
