# Generated by Django 3.2.25 on 2024-04-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20240401_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
