# Generated by Django 3.2.25 on 2024-04-01 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20240401_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesmetadatamiscfileupload',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_files', to='core.speciesmetadata'),
        ),
    ]
