# Generated by Django 3.2.25 on 2025-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_speciesmetadatamiscfileupload_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='request_immediate_approval',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='request_immediate_approval',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
