# Generated by Django 3.2.25 on 2025-03-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20250324_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalspeciesmetadata',
            name='request_immediate_approval',
        ),
        migrations.RemoveField(
            model_name='speciesmetadata',
            name='request_immediate_approval',
        ),
    ]
