# Generated by Django 3.2.25 on 2025-03-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20250324_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinelist',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalmetareference',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalspecies',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='linelist',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='metareference',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reference',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
