# Generated by Django 3.2.25 on 2025-03-27 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20250324_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalspeciesmetadata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical species metadata', 'verbose_name_plural': 'historical Species metadata'},
        ),
        migrations.AlterModelOptions(
            name='speciesmetadata',
            options={'verbose_name_plural': 'Species metadata'},
        ),
        migrations.AddField(
            model_name='historicallinelist',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='linelist',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metareference',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metareference_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speciesmetadata',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speciesmetadata_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
