# Generated by Django 3.2.25 on 2025-03-27 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20250327_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinelist',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicallinelist',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='historicallinelist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalmetareference',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicalmetareference',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='historicalmetareference',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalspecies',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicalspecies',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='historicalspecies',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='linelist',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='linelist',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_linelist', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='linelist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='metareference',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='metareference',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_metareference', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='metareference',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='reference',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reference', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='reference',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='species',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_species', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='species',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_speciesmetadata', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_speciesmetadatamiscfileupload', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
    ]
