# Generated by Django 3.2.25 on 2025-03-26 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20250326_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmetareference',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmetareference',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='historicalmetareference',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='historicalmetareference',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='historicalreference',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalreference',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='historicalspecies',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalspecies',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadata',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadata',
            name='linelist',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadata',
            name='species',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadata',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='linelist',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='linelist',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='metareference',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='metareference',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='species',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='species',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='speciesmetadata',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='speciesmetadata',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='speciesmetadatamiscfileupload',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='speciesmetadatamiscfileupload',
            name='rejected',
        ),
        migrations.AddField(
            model_name='linelist',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='linelist',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_linelist', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='linelist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='metareference',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='metareference',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_metareference', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='metareference',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='reference',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reference', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='reference',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='species',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_species', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='species',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_speciesmetadata', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='speciesmetadata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was approved or rejected', null=True),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_speciesmetadatamiscfileupload', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='speciesmetadatamiscfileupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', help_text='Approval status of the record', max_length=10),
        ),
        migrations.AlterField(
            model_name='metareference',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metareference_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speciesmetadata',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speciesmetadata_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speciesmetadatamiscfileupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speciesmetadatamiscfileupload_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalLinelist',
        ),
        migrations.DeleteModel(
            name='HistoricalMetaReference',
        ),
        migrations.DeleteModel(
            name='HistoricalReference',
        ),
        migrations.DeleteModel(
            name='HistoricalSpecies',
        ),
        migrations.DeleteModel(
            name='HistoricalSpeciesMetadata',
        ),
        migrations.DeleteModel(
            name='HistoricalSpeciesMetadataMiscFileUpload',
        ),
    ]
