# Generated by Django 3.2.25 on 2025-03-27 19:33

from django.db import migrations

def update_status_and_processed_by(apps, schema_editor):
    from django.conf import settings
    print("Updating status and processed_by fields")
    # Define status values (replace with your actual values)
    STATUS_APPROVED = 'approved'  # Adjust based on your model's STATUS_APPROVED
    STATUS_PENDING = 'pending'    # Adjust based on your model's STATUS_PENDING
    
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    
    try:
        default_user = User.objects.get(email='brettmc@mit.edu')  # Change this ID as needed
    except User.DoesNotExist:
        default_user = None

    # Loop through all historical models
    for model in apps.get_models():
        # Check if the model has the required fields
        field_names = [f.name for f in model._meta.get_fields()]
        if all(field in field_names for field in ["status", "approved", "processed_by"]):
            print(f"Updating {model.__name__}")
            
            instances = model.objects.all()
            for instance in instances:
                # Skip if already approved and status matches
                if instance.approved and instance.status == STATUS_APPROVED:
                    print(f"Skipping {instance} as it is already approved")
                    continue

                # Update status based on approved field
                instance.status = STATUS_APPROVED if instance.approved else STATUS_PENDING

                # Update processed_by if approved and not already set
                if instance.approved and not instance.processed_by and default_user:
                    instance.processed_by = default_user

                # Save the changes
                instance.save(update_fields=["status", "processed_by"])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20250327_0409'),
    ]

    operations = [
        migrations.RunPython(update_status_and_processed_by),
    ]