# Generated by Django 3.2.25 on 2025-03-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_update_status_processed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallinelist',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='historicalmetareference',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='historicalreference',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='historicalspecies',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadata',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='historicalspeciesmetadatamiscfileupload',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='linelist',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='metareference',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='species',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='speciesmetadata',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='speciesmetadatamiscfileupload',
            name='approved',
        ),
    ]
