# Generated by Django 3.2.25 on 2025-03-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_historicallinelist_historicalmetareference_historicalreference_historicalspecies_historicalspeciesme'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreference',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
